# Generated by Django 4.2.16 on 2024-12-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_remove_datosusuario_apellidousuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosusuario',
            old_name='profesionUsuario',
            new_name='profesion',
        ),
    ]
